### DISCUSSION TITLE
Release 2.4.0 - configuration wizard

### DISCUSSION THREAD

**Discussion by mathoudebine** [mathoudebine/turing-smart-screen-python#180] [Announcements]
### Configuration wizard
This release introduces the first version of the Configuration Wizard (#176).  
It offers an easy way to update the `config.yaml` file, as well as various checks and constraints on values (theme names, COM ports...) to avoid errors. The selected theme is also displayed as a preview.
<img src="https://user-images.githubusercontent.com/38615348/221564385-737d0b01-d439-4e24-9bb6-cce205958dc9.png" height="500" />   
This GUI is similar to what is offered by the original Windows program from screen manufacturers, and will offer a serious alternative for beginners wanting to use this program instead!
The wizard also offers a quick way to edit a selected theme from the Theme Editor, and to start the system monitor main program.

### Other changes
* Auto-commit theme previews on master/release push by @mathoudebine in https://github.com/mathoudebine/turing-smart-screen-python/pull/173
* text alignment by @cobacdavid in https://github.com/mathoudebine/turing-smart-screen-python/pull/172
* Allow custom date/time formatting from babel module by @mathoudebine in https://github.com/mathoudebine/turing-smart-screen-python/pull/174
```
    DAY: # Format (Y/M/D ordering, month/day translations...) will match your computer locale
      TEXT:
        FORMAT: medium # short (2/20/23) / medium (Feb 20, 2023) / long (February 20, 2023) / full (Monday, February 20, 2023)

    HOUR: # Format (12/24h, timezone translations) will match your computer locale
      TEXT:
        FORMAT: short # short (6:48 PM) / medium (6:48:53 PM) / long (6:48:53 PM UTC) / full (6:48:53 PM Coordinated Universal Time)
```
* Feature/176 add a configuration gui by @mathoudebine in https://github.com/mathoudebine/turing-smart-screen-python/pull/177

**Full Changelog**: https://github.com/mathoudebine/turing-smart-screen-python/compare/2.3.2...2.4.0

<hr /><em>This discussion was created from the release <a href='https://github.com/mathoudebine/turing-smart-screen-python/releases/tag/2.4.0'>Release 2.4.0 - configuration wizard</a>.</em>
