### DISCUSSION TITLE
The correct form of a theme.yaml

### DISCUSSION THREAD

**Discussion by ftk789** [mathoudebine/turing-smart-screen-python#189] [General]
Hey, I'm making a theme editor/maker in an electron app for this Community, I am trying to phrase YAML from JSON to YAML, The output of my functions show this YAML results

WARNING⚠LONG LIST AHEAD:

```
---
display:
  DISPLAY_ORIENTATION: reverse_landscape
  DISPLAY_RGB_LED: 255, 0, 0
  BACKGROUND:
    PATH: background.png
    X: 0
    Y: 0
    WIDTH: 320
    HEIGHT: 480
STATS:
  CPU:
    PERCENTAGE:
      INTERVAL: 1
      TEXT:
        SHOW: true
        SHOW_UNIT: true
        X: 240
        Y: 160
        FONT: geforce/GeForce-Bold.ttf
        FONT_SIZE: 122
        FONT_COLOR: 255, 255, 255
        BACKGROUND_IMAGE: background.png
      GRAPH:
        SHOW: false
        X: 115
        Y: 71
        WIDTH: 178
        HEIGHT: 13
        MIN_VALUE: 0
        MAX_VALUE: 100
        BAR_COLOR: 255, 0, 0
        BAR_OUTLINE: false
        BACKGROUND_IMAGE: background.png
    FREQUENCY:
      INTERVAL: 5
      TEXT:
        SHOW: false
        SHOW_UNIT: true
        X: 100
        Y: 87
        FONT: roboto/Roboto-Bold.ttf
        FONT_SIZE: 13
        FONT_COLOR: 200, 200, 200
        BACKGROUND_IMAGE: background.png
    LOAD:
      INTERVAL: 5
      ONE:
        TEXT:
          SHOW: false
          SHOW_UNIT: true
          X: 110
          Y: 106
          FONT: roboto/Roboto-Bold.ttf
          FONT_SIZE: 13
          FONT_COLOR: 200, 200, 200
          BACKGROUND_IMAGE: background.png
      FIVE:
        TEXT:
          SHOW: false
          SHOW_UNIT: true
          X: 183
          Y: 106
          FONT: roboto/Roboto-Bold.ttf
          FONT_SIZE: 13
          FONT_COLOR: 200, 200, 200
          BACKGROUND_IMAGE: background.png
      FIFTEEN:
        TEXT:
          SHOW: false
          SHOW_UNIT: true
          X: 265
          Y: 106
          FONT: roboto/Roboto-Bold.ttf
          FONT_SIZE: 13
          FONT_COLOR: 200, 200, 200
          BACKGROUND_IMAGE: background.png
    TEMPERATURE:
      INTERVAL: 5
      TEXT:
        SHOW: false
        SHOW_UNIT: true
        X: 154
        Y: 13
        FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
        FONT_SIZE: 23
        FONT_COLOR: 255, 255, 255
        BACKGROUND_IMAGE: background.png
  GPU:
    INTERVAL: 1
    PERCENTAGE:
      GRAPH:
        SHOW: false
        X: 115
        Y: 197
        WIDTH: 178
        HEIGHT: 13
        MIN_VALUE: 0
        MAX_VALUE: 100
        BAR_COLOR: 255, 0, 0
        BAR_OUTLINE: false
        BACKGROUND_IMAGE: background.png
      TEXT:
        SHOW: false
        SHOW_UNIT: true
        X: 250
        Y: 140
        FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
        FONT_SIZE: 23
        FONT_COLOR: 255, 255, 255
        BACKGROUND_IMAGE: background.png
    MEMORY:
      GRAPH:
        SHOW: false
        X: 115
        Y: 215
        WIDTH: 178
        HEIGHT: 13
        MIN_VALUE: 0
        MAX_VALUE: 100
        BAR_COLOR: 255, 0, 0
        BAR_OUTLINE: false
        BACKGROUND_IMAGE: background.png
      TEXT:
        SHOW: false
        SHOW_UNIT: true
        X: 204
        Y: 195
        FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
        FONT_SIZE: 23
        FONT_COLOR: 255, 255, 255
        BACKGROUND_IMAGE: background.png
    TEMPERATURE:
      TEXT:
        SHOW: false
        SHOW_UNIT: true
        X: 115
        Y: 231
        FONT: roboto/Roboto-Bold.ttf
        FONT_SIZE: 13
        FONT_COLOR: 200, 200, 200
        BACKGROUND_IMAGE: background.png
  MEMORY:
    INTERVAL: 5
    SWAP:
      GRAPH:
        SHOW: false
        X: 115
        Y: 285
        WIDTH: 178
        HEIGHT: 13
        MIN_VALUE: 0
        MAX_VALUE: 100
        BAR_COLOR: 255, 0, 0
        BAR_OUTLINE: false
        BACKGROUND_IMAGE: background.png
    VIRTUAL:
      GRAPH:
        SHOW: false
        X: 115
        Y: 303
        WIDTH: 178
        HEIGHT: 13
        MIN_VALUE: 0
        MAX_VALUE: 100
        BAR_COLOR: 255, 0, 0
        BAR_OUTLINE: false
        BACKGROUND_IMAGE: background.png
      USED:
        SHOW: false
        SHOW_UNIT: true
        X: 204
        Y: 290
        FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
        FONT_SIZE: 23
        FONT_COLOR: 255, 255, 255
        BACKGROUND_IMAGE: background.png
      FREE:
        SHOW: false
        SHOW_UNIT: true
        X: 182
        Y: 129
        FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
        FONT_SIZE: 23
        FONT_COLOR: 255, 255, 255
        BACKGROUND_IMAGE: background.png
      PERCENT_TEXT:
        SHOW: false
        SHOW_UNIT: true
        X: 250
        Y: 240
        FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
        FONT_SIZE: 23
        FONT_COLOR: 255, 255, 255
        BACKGROUND_IMAGE: background.png
  DISK:
    INTERVAL: 10
    USED:
      GRAPH:
        SHOW: false
        X: 115
        Y: 357
        WIDTH: 178
        HEIGHT: 13
        MIN_VALUE: 0
        MAX_VALUE: 100
        BAR_COLOR: 255, 0, 0
        BAR_OUTLINE: false
        BACKGROUND_IMAGE: background.png
      TEXT:
        SHOW: false
        SHOW_UNIT: true
        X: 204
        Y: 405
        FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
        FONT_SIZE: 23
        FONT_COLOR: 255, 255, 255
        BACKGROUND_IMAGE: background.png
      PERCENT_TEXT:
        SHOW: false
        SHOW_UNIT: true
        X: 46
        Y: 402
        FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
        FONT_SIZE: 23
        FONT_COLOR: 255, 255, 255
        BACKGROUND_IMAGE: background.png
    TOTAL:
      TEXT:
        SHOW: false
        SHOW_UNIT: true
        X: 204
        Y: 375
        FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
        FONT_SIZE: 23
        FONT_COLOR: 255, 255, 255
        BACKGROUND_IMAGE: background.png
    FREE:
      TEXT:
        SHOW: false
        SHOW_UNIT: true
        X: 204
        Y: 435
        FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
        FONT_SIZE: 23
        FONT_COLOR: 255, 255, 255
        BACKGROUND_IMAGE: background.png
  NET:
    INTERVAL: 1
    WLO:
      UPLOAD:
        TEXT:
          SHOW: false
          X: 4
          Y: 311
          FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
          FONT_SIZE: 23
          FONT_COLOR: 255, 255, 255
          BACKGROUND_IMAGE: background.png
      UPLOADED:
        TEXT:
          SHOW: false
          X: 90
          Y: 311
          FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
          FONT_SIZE: 23
          FONT_COLOR: 255, 255, 255
          BACKGROUND_IMAGE: background.png
      DOWNLOAD:
        TEXT:
          SHOW: false
          X: 4
          Y: 261
          FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
          FONT_SIZE: 23
          FONT_COLOR: 255, 255, 255
          BACKGROUND_IMAGE: background.png
      DOWNLOADED:
        TEXT:
          SHOW: false
          X: 90
          Y: 261
          FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
          FONT_SIZE: 23
          FONT_COLOR: 255, 255, 255
          BACKGROUND_IMAGE: background.png
    ETH:
      UPLOAD:
        TEXT:
          SHOW: false
          X: 254
          Y: 311
          FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
          FONT_SIZE: 23
          FONT_COLOR: 255, 255, 255
          BACKGROUND_IMAGE: background.png
      UPLOADED:
        TEXT:
          SHOW: false
          X: 192
          Y: 311
          FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
          FONT_SIZE: 23
          FONT_COLOR: 255, 255, 255
          BACKGROUND_IMAGE: background.png
      DOWNLOAD:
        TEXT:
          SHOW: false
          X: 254
          Y: 261
          FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
          FONT_SIZE: 23
          FONT_COLOR: 255, 255, 255
          BACKGROUND_IMAGE: background.png
      DOWNLOADED:
        TEXT:
          SHOW: false
          X: 192
          Y: 261
          FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
          FONT_SIZE: 23
          FONT_COLOR: 255, 255, 255
          BACKGROUND_IMAGE: background.png
  DATE:
    INTERVAL: 1
    DAY:
      TEXT:
        FORMAT: medium
        SHOW: false
        X: 10
        Y: 16
        FONT: roboto/Roboto-Bold.ttf
        FONT_SIZE: 13
        FONT_COLOR: 200, 200, 200
        BACKGROUND_IMAGE: background.png
    HOUR:
      TEXT:
        FORMAT: short
        SHOW: false
        X: 205
        Y: 13
        FONT: roboto/Roboto-Bold.ttf
        FONT_SIZE: 18
        FONT_COLOR: 200, 200, 200
        BACKGROUND_IMAGE: background.png
```
 
Is there anything wrong with it? Whenever I pass it tot he theme-editor.py, It just says " No such theme or theme has errors "
Thanks in advance.
