### DISCUSSION TITLE
How to monitor the power of CPU/GPU in watts with this software. Or is that possible?

### DISCUSSION THREAD

**Discussion by Yu0413** [mathoudebine/turing-smart-screen-python#248] [Q&A]
Hi, I recently bought this set of small monitor screens because I enjoy monitoring the hardware status of my computer. 
However, I noticed that none of the default themes have the ability to display CPU and GPU power in watts. 
I was wondering if this alternative software can achieve that?

I understand that I can find all the available items in the theme examples, but it seems that power is not included. 
Is it possible to add power monitoring? 
Or is this item not capturing power values at the core level?
Can you help me with how to proceed?
 Thank you.

**Comment by Queven** [comment]
I'd like to know that too

**Comment by Jidoeuf** [comment]
Hi,

I did it by adding in sensors_custom.py the code below. Maybe you have to adjust the sensor Name search depending on what you can see in the LibreHardwareMonitor report (check sensors_custom wiki)
Maybe some easier solution exists but at least this one I created works for me.

```
class GPUPOWER(CustomDataSource):
    def as_numeric(self) -> float:    
        gpu = get_hw_and_update(Hardware.HardwareType.GpuNvidia)
               
        for sensor in gpu.Sensors:
            if "Package" in str(sensor.Name) : 
                return float(sensor.Value)

        logger.error("GPU Power cannot be read")
        return math.nan
            
    def as_string(self) -> str:
        return f'{int(self.as_numeric()):>3} W'
```
        

```
class CPUPOWER(CustomDataSource):
    def as_numeric(self) -> float:    
        cpu = get_hw_and_update(Hardware.HardwareType.Cpu)             
        for sensor in cpu.Sensors:
            if "Package" in str(sensor.Name) : 
                return float(sensor.Value)

        logger.error("CPU Power cannot be read")
        return math.nan
            
    def as_string(self) -> str:
        return f'{int(self.as_numeric()):>3} W'   
```




After that you can simply use them in the theme.yaml with something like that :
```
    GPUPOWER:
      TEXT:
        SHOW: True
        SHOW_TEXT: True
        SHOW_UNIT: True
        X: 240
        Y: 295
        FONT: generale-mono/GeneraleMonoA.ttf
        FONT_SIZE: 15
        FONT_COLOR: 2, 216, 243
        BACKGROUND_IMAGE: background_new.png
    CPUPOWER:
      TEXT:
        SHOW: True
        SHOW_TEXT: True
        SHOW_UNIT: True
        X: 70
        Y: 295
        FONT: generale-mono/GeneraleMonoA.ttf
        FONT_SIZE: 15
        FONT_COLOR: 2, 216, 243
        BACKGROUND_IMAGE: background_new.png
```
