### DISCUSSION TITLE
About FPS indicator..

### DISCUSSION THREAD

**Discussion by ooemir23** [mathoudebine/turing-smart-screen-python#327] [Q&A] [answered]
Hello,
I can see FPS in games on the Xuanfang 3.5 Mini screen I use.
Is it possible to see through this beautiful project?

**Comment by mathoudebine** [comment]
Hello @ooemir23 
I have looked at Xuanfang software and it seems they are using the same library to get GPU info as this project.
It is then possible to add the FPS meters to this project!
I will work on it now

**Comment by mathoudebine** [comment, marked as answer]
Hello again,
This has now been implemented to the latest 3.3.1 release.
Feel free to try it out and add the FPS framerate to your favorite theme!

Please note it is for now limited to Windows platforms and AMD GPUs

**Reply by ooemir23** [reply]
Thank you for your concern. I have very little Python knowledge but I can copy and paste features from other themes. Which command should I enter to show FPS?

Sanırım buldum,
FPS:
      TEXT:
        SHOW: False
        SHOW_UNIT: False

**Reply by mathoudebine** [reply]
In your theme.yaml you need to add FPS inside STATS / GPU:
```yaml

STATS:
  [...]

  GPU:
    INTERVAL: 1
    [...] 
    FPS:
      TEXT:
        SHOW: True
        SHOW_UNIT: True
        X: 10
        Y: 10
        FONT: roboto/Roboto-Bold.ttf
        FONT_SIZE: 13
        FONT_COLOR: 200, 200, 200
        # BACKGROUND_COLOR: 50, 50, 50
        BACKGROUND_IMAGE: background.png
```
