### DISCUSSION TITLE
[3.5" portrait] Modified Pink (Purple) Plexus theme

### DISCUSSION THREAD

**Discussion by jimaiwr** [mathoudebine/turing-smart-screen-python#436] [Themes]
![image](https://github.com/mathoudebine/turing-smart-screen-python/assets/59927023/5f1db136-abf9-4a28-990b-9f8a55715cf0)

[Pink Plexus edit.zip](https://github.com/mathoudebine/turing-smart-screen-python/files/13840472/Pink.Plexus.edit.zip)

Just a quick one and might do more in the future, it's really purple if you ask me..
Awesome finding this git today though thanks Mathoudebine.

Oh and noticed I am getting an undefined character in the time, any ideas? 
lastly would love to have CPU and GPU temp graphs please let me know if this is possible. Thanks all!
![image](https://github.com/mathoudebine/turing-smart-screen-python/assets/59927023/8122c1e2-16aa-4a7f-bdf0-3409d7f67102)

**Comment by viitinho3d** [comment]
How to install?

**Comment by c0ldJS** [comment]
> "... would love to have CPU and GPU temp graphs..."

Totally doable. Here are some example snippets for `theme.yaml` to get you started:

```
#For a horizontal bar:
      GRAPH:
        SHOW: True
        X: 20
        Y: 150
        WIDTH: 100
        HEIGHT: 25
        MIN_VALUE: 20
        MAX_VALUE: 100
        BAR_COLOR: 255, 255, 255
        BAR_OUTLINE: False

#For a line graph showing changes over time:
      LINE_GRAPH:
        SHOW: True
        X: 20
        Y: 180
        WIDTH: 100
        HEIGHT: 25
        MIN_VALUE: 20
        MAX_VALUE: 100
        HISTORY_SIZE: 20
        AUTOSCALE: True
        LINE_COLOR: 255, 184, 89
        AXIS: False
        AXIS_COLOR: 0, 0, 0
```
Plenty of room to customize. Hope this helps.
