### DISCUSSION TITLE
Make the Smart Screen interactive (adding buttons)

### DISCUSSION THREAD

**Discussion by caerffili** [mathoudebine/turing-smart-screen-python#494] [Ideas]
I've not been able to find anything regarding interacting with the Smart Screen so I'm sounding out the idea of making the Smart Screen interactive.

In addition to system monitoring, I'd love to be able to use these screens to interact with my Home Assistant setup for home control, by 3d printing a nice case complete with a Raspberry Pi Zero of some sort and a few physical buttons wired to the Pi.

I'm thinking of adding menu functionality (as the bottom of the screen shot) which would match up with the physical buttons on the case.

![preview](https://github.com/mathoudebine/turing-smart-screen-python/assets/32393643/59273afa-53a3-46e3-9db2-d1e6e07e97be)

When a button is pressed one or more actions can take place such as-

- Increase or decrease the screen brightness
- Fire off an MQTT message to a MQTT server. This can be used to control or interact with other things such as turn on the room lights
- Call a web api
- Open up a sub menu
- Hide or show screen elements, so could for example toggle a graph between CPU usage and memory usage

This would be controlled with a new MENU section in the theme config, e.g.

```
MENU:
  ROOT:
    B1:
      MENULABEL: " CPU/RAM "
      ACTION:
        SUBMENU: LeftMenu
      TEXT: 
        SHOW: True
        X: 80 
        Y: 292
        FONT: roboto-mono/RobotoMono-Bold.ttf
        FONT_SIZE: 23
        FONT_COLOR: 248, 177, 51
        BACKGROUND_IMAGE: background.png
      B2:
      MENULABEL: " OIL/PWR "
      ACTION:
        SUBMENU: RightMenu
      TEXT:
        SHOW: True
        X: 300
        Y: 292
        FONT: roboto-mono/RobotoMono-Bold.ttf
        FONT_SIZE: 23
        FONT_COLOR: 248, 177, 51
        BACKGROUND_IMAGE: background.png        

  LeftMenu:
    B1:
      MENULABEL: "   CPU   "
      ACTION:
        SHOW_ELEMENT:
          - ELEMENT: STATS,CPU,PERCENTAGE,RADIAL
        HIDE_ELEMENT: 
          - ELEMENT: STATS,MEMORY,VIRTUAL,RADIAL
        BRIGHTNESS_DECREASE: 
        SUBMENU: ROOT
      TEXT: 
        SHOW: True
        X: 80 
        Y: 292
        FONT: roboto-mono/RobotoMono-Bold.ttf
        FONT_SIZE: 23
        FONT_COLOR: 248, 177, 51
        BACKGROUND_IMAGE: background.png
    B2:
      MENULABEL: "   RAM   "
      ACTION:
        HIDE_ELEMENT:
          - ELEMENT: STATS,CPU,PERCENTAGE,RADIAL
        SHOW_ELEMENT:
          - ELEMENT: STATS,MEMORY,VIRTUAL,RADIAL
        SUBMENU: ROOT
      TEXT:
        SHOW: True
        X: 300
        Y: 292
        FONT: roboto-mono/RobotoMono-Bold.ttf
        FONT_SIZE: 23
        FONT_COLOR: 248, 177, 51
        BACKGROUND_IMAGE: background.png
```

I'm not sure if this use is edge case or if others would like this type of functionality, ~~it's obviously limited to devices with the ability to connect physical buttons to, such as a Raspberry Pi. Although there could be options to intercept keyboard strokes or interface with a Stream Deck on a PC.~~ EDIT - key press events work fine on Windows and RPi while running in the background, so it can be setup to intercept key presses with modifiers, so for example, ctrl+alt+1 etc can be used to select menu entries.

I've got most of this working in a fork, if it's of interest (and not scope creeping this project too far) I can try to do a pull request?
