### DISCUSSION TITLE
Hostname/IP information

### DISCUSSION THREAD

**Discussion by KillerBus** [mathoudebine/turing-smart-screen-python#526] [Q&A]
Hi,

I'm really not very good with Python etc... would anyone be able to help me in how I would pull in hostname and local (192.x.x.x) IP address please?

Thanks
John

**Comment by c0ldJS** [comment]
For a lowdown throwdown kludge to get you where you want to go superfast, there are two files you'll want to edit.

<details><summary>~\library\sensors\sensors_custom.py</summary>
<p>

```
import socket
```

```
class MyLocalhost(CustomDataSource):
    def as_numeric(self) -> float:
        # If there is no numeric value, keep this function empty
        pass
    def as_string(self) -> str:
        # If a custom data class only has text values, it won't be possible to display graph or radial bars
        return socket.gethostname()
    def last_values(self) -> List[float]:
        # If a custom data class only has text values, it won't be possible to display line graph
        pass
```

```
class MyLocalAddr(CustomDataSource):
    def as_numeric(self) -> float:
        # If there is no numeric value, keep this function empty
        pass
    def as_string(self) -> str:
        # If a custom data class only has text values, it won't be possible to display graph or radial bars
        return socket.gethostbyname(socket.gethostname())
    def last_values(self) -> List[float]:
        # If a custom data class only has text values, it won't be possible to display line graph
        pass
```
</p>
</details>
<details><summary>~\theme.yaml</summary>
<p>

```
  CUSTOM:
    INTERVAL: 10
    MyLocalhost:
      TEXT:
        SHOW: True
        X: 50
        Y: 310
        FONT: [RELEVANT TYPEFACE]
        FONT_SIZE: 21
        FONT_COLOR: 66, 55, 77
        # BACKGROUND_COLOR: 0, 0, 0
        BACKGROUND_IMAGE: [RELEVANT IMAGE]
    MyLocalAddr:
      TEXT:
        SHOW: True
        X: 50
        Y: 365
        FONT: [RELEVANT TYPEFACE]
        FONT_SIZE: 21
        FONT_COLOR: 66, 55, 77
        # BACKGROUND_COLOR: 0, 0, 0
        BACKGROUND_IMAGE: [RELEVANT IMAGE]
```
</p>
</details>

Salt and season to taste. Very few computers make it a habit of changing their hostname regularly; you might be better off with sticking it permanently inside a `static_text` stanza in `theme.yaml` instead.
