### DISCUSSION TITLE
Unraid instal docker.

### DISCUSSION THREAD

**Discussion by FloydKulis** [mathoudebine/turing-smart-screen-python#607] [Q&A]
Trying to install turing smart screen on Unraid:
![image](https://github.com/user-attachments/assets/435b6a85-ce25-41a2-bb40-738cb1f3b223)

I found my USB connected to the motherboard:
![image](https://github.com/user-attachments/assets/e2fae777-86f7-4f94-b944-4e0d2b7103dd)

My log file affter start aplication:
```
11/19/24 17:19:33 [INFO] Loading theme Cyberpunk-net from res/themes/Cyberpunk-net/theme.yaml
11/19/24 17:19:34 [DEBUG] HW revision: A
11/19/24 17:19:34 [ERROR] Cannot find COM port automatically, please run Configuration again and select COM port manually
Your config.yaml:
config:
  COM_PORT: "AUTO"
  THEME: Cyberpunk-net
  HW_SENSORS: AUTO
  ETH: eth0 # Ethernet Card
  WLO: "" # Wi-Fi Card
  CPU_FAN: AUTO
display:
  REVISION: A
  BRIGHTNESS: 40
  DISPLAY_REVERSE: false
======================= STARTING APP =======================
```
I tried changing the config.yaml file and entering COM_PORT there, but every time I restart the application the file returns to the same one.

Maybe some of you have Turing on Unraid and know how to install it to make the monitor work?
