### DISCUSSION TITLE
Multiline text from custom sensor

### DISCUSSION THREAD

**Discussion by EdvanSchleck5** [mathoudebine/turing-smart-screen-python#772] [Q&A] [answered]
Hi, i am new to python and tried to get my steam friends on the display and what game they are playing at the moment. 
My string contains multiline text. When i try to get in on the display, i get the following error: " Error in theme: anchor not supported for multiline text"

So my question is, does it support multiline and what do i have to do to get in on the screen?

**Comment by mathoudebine** [comment, marked as answer]
Did you implement it in a custom sensor? The issue may be because if no answer is specified then the default anchor 'lt' is applied, but the 'lt' anchor is incompatible with multiline text.

In your theme file you could try to specify another text anchor like this:
```yaml
  CUSTOM:
    INTERVAL: 3
    YourCustomSensor:
      TEXT:
        [...]
        ANCHOR: 'la'
```
