### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by cobacdavid** [mathoudebine/turing-smart-screen-python#171]
As `DisplayText` method accept multiline text, I suggest to add a `align` option (or `justify`). It allows to align correctly different lines of text without having to calculate spaces.
So 3 values to this options: `left` (default), `center` and `right`:

<img width=200px src="https://user-images.githubusercontent.com/7426305/220089201-e8f64f49-17a4-4a0a-854a-5223b08621f3.png" /> <img width=200px src="https://user-images.githubusercontent.com/7426305/220089657-d478e76a-8464-4a8a-b3ef-e7a9f7463d97.png"/> <img width=200px src="https://user-images.githubusercontent.com/7426305/220089861-ba6f857f-00a9-4dfb-88e5-a25c31122836.png" />

It's easy to produce: `Context.text` method accept `align` option. Is it relevant to PR this feature?

**Comment by mathoudebine** [comment]
This would be a great addition!
It could then be added to the `static_text` of the theme files:
```yaml
static_text:
  TEXT_EXAMPLE:
   TEXT: Add your custom text here!
   X: 20
   Y: 400
   FONT: geforce/GeForce-Bold.ttf
   FONT_SIZE: 20
   FONT_COLOR: 255, 255, 255
   BACKGROUND_IMAGE: background.png
   ALIGN: center
```
However it would not be used for sensor metrics as they need to be right-aligned so that the unit stays in the same place when the value grows/decreases.
