### ISSUE TITLE
Add date and time format in theme settings

### ISSUE THREAD

**Issue by nukdokplex** [mathoudebine/turing-smart-screen-python#239]
**Is your feature request related to a problem? If so, please describe the problem.**  
Because of my localization python generates date with symbols, that do not exist in font. And also i don't want to see date and time in this format. 

**Describe the feature / solution to your problem you'd like**  
Add date and time format option to theme yml structure. Something like ``dd.mm.YY``.

**Describe alternatives you've considered / and or tested**  
I have no time to do it myself.=

**Screenshots / photos & mockups of the Turing screen**  
![image](https://github.com/mathoudebine/turing-smart-screen-python/assets/25458915/3d0e8b95-edc3-4e40-ae1c-6abbaa9dbe93)
as you can see in the bottom of the screen there's unprintable symbols

**Environment:**  
 - Project 2.4.2
 - Manjaro latest 2023/05/25
 - Python 3.10
 - See screenshot :)

**Additional context**

**Comment by mathoudebine** [comment]
Hello, this feature is already included but it has not yet been added to all the themes.
If you have a look at `res/themes/theme_example.yaml` you can see a `FORMAT` setting for `DAY` and `HOUR` entries:
```yaml
  DATE:
    DAY: # Format (Y/M/D ordering, month/day translations...) will match your computer locale
      TEXT:
        FORMAT: medium # short (2/20/23) / medium (Feb 20, 2023) / long (February 20, 2023) / full 
[...]

    HOUR: # Format (12/24h, timezone translations) will match your computer locale
      TEXT:
        FORMAT: short # short (6:48 PM) / medium (6:48:53 PM) / long (6:48:53 PM UTC) / full (6:48:53 PM Coordinated Universal Time)
[...]
```

in your case, you can add `FORMAT: short` to the `DAY` entry of your theme and you will have the date short format based on your locale.

There is custom formatting (like yy.mm.dd or dd.mm.yy) for date/time for the moment, because the base date/time formatting depends on the computer locale.
