### ISSUE TITLE
Weather addition in standard theme?

### ISSUE THREAD

**Issue by naddel91** [mathoudebine/turing-smart-screen-python#795]
Hi at all,

first of all: thanks for the great plugin. But how do I get this:

https://raw.githubusercontent.com/mathoudebine/turing-smart-screen-python/main/res/themes/5inchTheme2/preview.png

to show up on my 3.5 inch turing screen? I even made the longitude addition in the editor, but it only shows disk (which I am not interested in) instead of weather.

Any help is highly appreciated. 

Thanks in advance!

**Comment by ColinShorts** [comment]
If you look in res/themes you'll find the files in the 3.5inchTheme2 and 5inchTheme2 directories, the weather and disk icons are part of the background.png, so you'd need to edit the background files in addition to hiding or removing the disk config, and adding the weather config to theme.yaml (note: you'll need to adjust the z/y values as the 3.5" screen has a lot less pixels).
```
  WEATHER:
    # For optimal use, if you don't want to trigger the free threshold daily call (1000 calls), the interval should be 90 MINIMUM (not really useful as the API didn't update that quickly)
    INTERVAL: 300
    TEMPERATURE:
      TEXT:
        SHOW: True
        X: 105
        Y: 445
        FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
        FONT_SIZE: 25
        FONT_COLOR: 255, 255, 255
        BACKGROUND_IMAGE: background.png 
        WIDTH: 200
        ANCHOR: rt
    WEATHER_DESCRIPTION:
      TEXT:
        SHOW: True
        X: 105
        Y: 415
        FONT: jetbrains-mono/JetBrainsMono-Bold.ttf
        FONT_SIZE: 25
        FONT_COLOR: 255, 255, 255
        BACKGROUND_IMAGE: background.png 
        WIDTH: 200
        ANCHOR: rt
```
A little bit of trial and error is required, but once you get started it's not too bad to get things working.
